import type { NextPage } from 'next'
import Head from 'next/head'
import Image from "next/future/image";
import Hero from "../src/Hero.webp"

const Home: NextPage = () => {
  const blurDataUrl = "data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAALABQDASIAAhEBAxEB/8QAGAAAAwEBAAAAAAAAAAAAAAAAAAQHAwX/xAAhEAACAQQCAgMAAAAAAAAAAAABAgMABAURBhIhMRNxkf/EABYBAQEBAAAAAAAAAAAAAAAAAAQAA//EABsRAAIDAQEBAAAAAAAAAAAAAAECAAMEMQUR/9oADAMBAAIRAxEAPwBDH8fz0xb4NwQ7HUSN51TdxwXMTHbXNs69+x7N6+q7GFup5MbC7yuzFfJJreO5mLtuRv2k5sdboGPYW7XYjkCRPI8kyWMv7izjVgsLlRtSd6Puiq7d2VtPMXmgjdyPZWitD5qyG8/OT//Z"

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div style={{
        width: "100%",
        height: "100%"
      }}>
        <Image
        src={"https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Tours_Place_Plumereau_1.jpg/1920px-Tours_Place_Plumereau_1.jpg"}
        alt=""
        sizes="100vw"
        priority
        fill
        style={{ objectFit: "cover" }}
        placeholder="blur"
        blurDataURL={blurDataUrl}
      />

      </div>
    </div>
  )
}

export default Home
